### ISSUE TITLE
JsonReader doesn't pass trailing decimals like 1.0 as valid JSON

### ISSUE THREAD

**Issue by Fourmisain** [QuiltMC/quilt-json5#5]
From https://github.com/Fourmisain/CreativeOnePunch/issues/1

## Issue

`JsonReader` doesn't pass numbers with trailing zero decimals like `1.0` as valid JSON in "strict mode", which is e.g. used for `mod.json` files.

### Why trailing zero decimals are valid JSON

The tl;dr is that standard says so, there's only 1 number type, "number" (so no distinction between floating point and integers), which is allowed to have trailing decimals and there is not restriction on the decimal part having the value 0.
For (very short) specs, see [RFC 8259 ](https://datatracker.ietf.org/doc/html/rfc8259), [ECMA-404](https://www.ecma-international.org/publications-and-standards/standards/ecma-404/) and [ISO/IEC 21778:2017](https://www.iso.org/standard/71616.html) or [json.org](https://www.json.org).

### Where `JsonReader` fails

The reader throws an `MalformedSyntaxException` via `isJson5()` after parsing the literal `1.0` when it reaches
https://github.com/QuiltMC/quilt-json5/blob/4e9caa0e5a1c438ac89e683454b8214a8c341163/src/main/java/org/quiltmc/json5/JsonReader.java#L1154

The reason why it thinks `last == NUMBER_CHAR_DECIMAL` is because when encountering the `0`, [it does not update the `last` variable](https://github.com/QuiltMC/quilt-json5/blob/4e9caa0e5a1c438ac89e683454b8214a8c341163/src/main/java/org/quiltmc/json5/JsonReader.java#L1099-L1101).

Hence the reader treats the literal `1.0` as the same as `1.`, the latter being illegal JSON, the former not.

Just as a reference, this issue seems to have been introduced in https://github.com/QuiltMC/quilt-json5/commit/ccfa2421de4de72982af8fe9afdf80641d246d02.

**Comment by EGOIST1372** [comment]
@TheGlitch76 any news on fixing this?

**Comment by TheGlitch76** [comment]
This should have been resolved with https://github.com/QuiltMC/quilt-json5/commit/c6e40e739f7fa47f292daaa81eeaea60f0a9ebd5, now released as `1.0.3` (I forgot to hit the button!)
